---
Metrics/LineLength:
  Max: 130

Metrics/ParameterLists:
  Max: 10

Naming/AccessorMethodName:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/StructInheritance:
  Enabled: false
